@file:Suppress("UnusedReceiverParameter")

package org.meteora.presentation.icon.weather

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val WeatherIcons.HeavySnow: ImageVector
    get() {
        if (_HeavySnow != null) {
            return _HeavySnow!!
        }
        _HeavySnow = ImageVector.Builder(
            name = "HeavySnow",
            defaultWidth = 96.dp,
            defaultHeight = 90.dp,
            viewportWidth = 96f,
            viewportHeight = 90f
        ).apply {
            path(fill = SolidColor(Color.White)) {
                moveTo(60.754f, 6.102f)
                curveToRelative(2.716f, 2.11f, 4.357f, 4.094f, 6.059f, 7.086f)
                curveToRelative(2.792f, 3.59f, 4.63f, 3.614f, 8.945f, 4.335f)
                curveTo(81.809f, 18.81f, 85.483f, 23.277f, 89f, 28f)
                curveToRelative(1.96f, 5.88f, 1.828f, 12.603f, -0.187f, 18.438f)
                curveTo(85.27f, 51.446f, 81.768f, 54.822f, 76f, 57f)
                curveToRelative(-4.426f, 0.457f, -8.835f, 0.444f, -13.281f, 0.434f)
                lineToRelative(-3.9f, 0.015f)
                quadToRelative(-4.074f, 0.013f, -8.15f, -0.003f)
                curveToRelative(-3.47f, -0.011f, -6.939f, 0.009f, -10.41f, 0.038f)
                curveToRelative(-3.325f, 0.023f, -6.651f, 0.016f, -9.978f, 0.012f)
                lineToRelative(-3.76f, 0.034f)
                curveTo(15.834f, 57.444f, 15.834f, 57.444f, 11f, 53f)
                curveToRelative(-3.228f, -3.86f, -4.34f, -8.013f, -4.187f, -13f)
                curveToRelative(0.83f, -5.66f, 3.866f, -9.387f, 8.187f, -13f)
                lineToRelative(3f, -1f)
                curveToRelative(0.998f, -2.293f, 0.998f, -2.293f, 1.75f, -5.062f)
                curveToRelative(2.465f, -7.218f, 6.357f, -12.422f, 12.938f, -16.375f)
                curveTo(41.683f, 0.319f, 52.248f, 0.759f, 60.754f, 6.102f)
            }
            path(fill = SolidColor(Color.White)) {
                moveTo(65f, 62f)
                horizontalLineToRelative(3f)
                lineToRelative(1f, 2f)
                curveToRelative(2.025f, 0.652f, 2.025f, 0.652f, 4f, 1f)
                lineToRelative(-0.5f, 1.75f)
                curveToRelative(-0.645f, 2.517f, -0.645f, 2.517f, -0.5f, 6.25f)
                lineToRelative(-4f, -1f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-3f)
                lineToRelative(-4f, 1f)
                verticalLineToRelative(-4f)
                arcToRelative(69f, 69f, 0f, isMoreThanHalf = false, isPositiveArc = false, -1f, -4f)
                lineToRelative(3f, -1f)
                lineToRelative(2f, 1f)
                close()
                moveTo(45f, 62f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(3f)
                lineToRelative(4f, -1f)
                verticalLineToRelative(4f)
                arcToRelative(69f, 69f, 0f, isMoreThanHalf = false, isPositiveArc = false, 1f, 4f)
                lineToRelative(-3f, 1f)
                lineToRelative(-2f, -1f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-3f)
                lineToRelative(-4f, 1f)
                verticalLineToRelative(-4f)
                arcToRelative(69f, 69f, 0f, isMoreThanHalf = false, isPositiveArc = false, -1f, -4f)
                lineToRelative(3f, -1f)
                lineToRelative(2f, 1f)
                close()
                moveTo(18f, 75f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(4f)
                lineToRelative(5f, -1f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-4f)
                lineToRelative(-1f, 3f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-3f)
                horizontalLineToRelative(-4f)
                lineToRelative(0.563f, -1.75f)
                curveToRelative(0.477f, -2.457f, 0.194f, -3.894f, -0.563f, -6.25f)
                horizontalLineToRelative(3f)
                close()
                moveTo(58f, 75f)
                horizontalLineToRelative(2f)
                lineToRelative(1f, 3f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-4f)
                lineToRelative(-1f, 3f)
                horizontalLineToRelative(-3f)
                lineToRelative(-1f, -3f)
                curveToRelative(-2.015f, -0.733f, -2.015f, -0.733f, -4f, -1f)
                lineToRelative(2f, -3f)
                curveToRelative(-0.308f, -2.153f, -0.308f, -2.153f, -1f, -4f)
                horizontalLineToRelative(3f)
                close()
                moveTo(38f, 75f)
                horizontalLineToRelative(2f)
                lineToRelative(1f, 3f)
                horizontalLineToRelative(4f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-2f)
                verticalLineToRelative(2f)
                horizontalLineToRelative(2f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-4f)
                lineToRelative(-1f, 3f)
                horizontalLineToRelative(-3f)
                lineToRelative(-1f, -3f)
                curveToRelative(-2.015f, -0.733f, -2.015f, -0.733f, -4f, -1f)
                lineToRelative(2f, -3f)
                curveToRelative(-0.308f, -2.153f, -0.308f, -2.153f, -1f, -4f)
                horizontalLineToRelative(3f)
                close()
                moveTo(25f, 62f)
                horizontalLineToRelative(3f)
                verticalLineToRelative(3f)
                lineToRelative(4f, -1f)
                verticalLineToRelative(4f)
                arcToRelative(69f, 69f, 0f, isMoreThanHalf = false, isPositiveArc = false, 1f, 4f)
                lineToRelative(-3f, 1f)
                lineToRelative(-2f, -1f)
                verticalLineToRelative(3f)
                horizontalLineToRelative(-3f)
                verticalLineToRelative(-3f)
                lineToRelative(-4f, 1f)
                lineToRelative(0.563f, -2.25f)
                curveToRelative(0.429f, -2.7f, 0.288f, -4.196f, -0.563f, -6.75f)
                horizontalLineToRelative(3f)
                close()
            }
        }.build()

        return _HeavySnow!!
    }

@Suppress("ObjectPropertyName")
private var _HeavySnow: ImageVector? = null
